title: Kunal Nagar
description: Hi. I'm Kunal. Use JavaScript responsibly and help make the web fast.
baseurl: ''
url: 'https://www.kunalnagar.in'

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

permalink: pretty
destination: ./release
plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - node_modules
  - vendor

sass:
  implementation: sass-embedded
  load_paths:
    - _sass
    - node_modules
  style: compressed
